--- 
- name: Setting Up RPM Fusion
  package: name={{ item }} state=present
  with_items:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ release }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ release }}.noarch.rpm


- name: Installing Multimedia Packages
  package: name={{ item }} state=present
  with_items:
    - ffmpeg
    - gstreamer
    - gstreamer-ffmpeg
    - gstreamer-plugins-good
    - gstreamer-plugins-ugly
    - gstreamer-plugins-bad-free
    - gstreamer1-libav
    - gstreamer1-plugins-good
    - gstreamer1-plugins-ugly
   

- name: Installing System Utilities
  package: name={{ item }} state=present
  with_items:
    - vim
    - nmap
    - tmux
    - unar
    - flatpak
    - redshift
    - keepassx
    - youtube-dl
    - overpass-fonts
    - overpass-mono-fonts
    - python2-libselinux


- name: Setting Up Flathub (Flatpak Repository)
  command:
  args:
     argv:
        - flatpak
        - remote-add
        - --if-not-exists
        - flathub
        - https://flathub.org/repo/flathub.flatpakrepo


- name: Full System Update
  package: name=* state=latest
