--- 
- name: Identifying GPU
  shell: "lspci | grep VGA | cut -d: -f3"
  register: systemGPU
  tags:
    - gpu

- debug: var=systemGPU.stdout
  tags:
    - gpu

- set_fact: gpu={{ systemGPU }}


- name: Setting Up RPM Fusion
  package: name={{ item }} state=present
  with_items:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ release }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ release }}.noarch.rpm


- name: Installing Multimedia Packages
  package: name={{ item }} state=present
  with_items:
    - ffmpeg
    - gstreamer
    - gstreamer-ffmpeg
    - gstreamer-plugins-good
    - gstreamer-plugins-ugly
    - gstreamer-plugins-bad-free
    - gstreamer1-libav
    - gstreamer1-plugins-good
    - gstreamer1-plugins-ugly


- name: Enabling Hardware Decoding
  package: name={{ item }} state=present
  with_items:
    - libva-utils
    - libvdpau-va-gl
    - libva-intel-driver
  when: "{{ gpu }}" == "Intel"


- name: Installing System Utilities
  package: name={{ item }} state=present
  with_items:
    - vim
    - nmap
    - tmux
    - unar
    - flatpak
    - redshift
    - keepassx
    - youtube-dl
    - google-noto-mono-fonts
    - google-noto-sans-mono-fonts
    - google-noto-sans-fonts
    - adobe-source-code-pro-fonts # Source Code Pro font, for Konsole, Kate & KDevelop
    - python2-libselinux


- name: Setting Up Flathub (Flatpak Repository)
  command:
  args:
     argv:
        - flatpak
        - remote-add
        - --if-not-exists
        - flathub
        - https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - flathub


- name: Full System Update
  package: name=* state=latest
  tags:
    - updateOS
