--- 
- name: Removing unneeded applications
  package: name={{ item }} state=absent
  with_items:
    - kmail
    - jovie
    - knode
    - kruler
    - dragon
    - amarok
    - kmouth
    - krusader
    - akregator
    - konqueror
    - dnfdragora
    - libkdegames
    - konversation
    - kcolorchooser
    - telepathy-qt5
    - calligra-core
    - kwalletmanager

- name: Installing Applications
  package: name={{ item }} state=present
  with_items:
    - plasma-workspace-wayland
    - plasma-applet-redshift-control
