---
# https://store.docker.com/editions/community/docker-ce-server-fedora
- name: Removing Old/Previous Docker Versions (Non Community)
  package: name={{ item }} state=absent
  with_items:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-selinux
      - docker-engine  


- name: Adding Docker CE Repository
  command: 
  args:
      argv:
         - dnf 
         - config-manager
         - --add-repo
         - https://download.docker.com/linux/fedora/docker-ce.repo


- name: Installing Docker CE
  package:
    name: docker-ce
    state: present


#TODO docker-compose release version is fixed, automate this
- name: Installing docker-compose
  command:
  args:
      argv:
          - sudo
          - curl
          - -L
          - "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)"  
          - -o
	  - /usr/local/bin/docker-compose


- name: Enabling Docker Service
  service:
      name: docker
      enabled: yes
      state: started


#https://serverfault.com/questions/542910/adding-a-user-to-an-additional-group-using-ansible#548392
- name: Adding "{{ user }}" to Docker Group
  user:
      name: "{{ user }}"
      groups: docker
      append: yes

