--- 
- name: Installing IDE
  package: name={{ item }} state=present
  with_items:
    - kdevelop
    - kdevelop-python


- name: Enabling Virtualization
  dnf: 
    name: '@virtualization'
    state: present


- name: Starting Virtualization service
  service:
      name: libvirtd
      state: started


# If user is logged in, then logout and log in again load the changes to the account
- name: Adding "{{ user }}" to Virtualization Group
  user:
      name: "{{ user }}"
      groups: libvirt
      append: yes
