---
- name: Creating student users
  user:
    create_home: yes
    name: "{{ item }}"
    password: '$5$sFAi5TotwGzXXCrH$/RHivI2xEZy1bxDpXdpRWWwpx0U/dIWARmItHzuMog9'
    state: present
  with_items:
    - estudiante1
    - estudiante2
    - estudiante3
    - estudiante4
    - estudiante5
    - estudiante6

